### ISSUE TITLE
cool idea & license

### ISSUE THREAD

**Issue by camaeel** [c0depool/c0depool-iac#1]
Cool idea to build talos template with packer. 
Could you add some official opensource license to this repo?

**Comment by c0depool** [comment]
Hi @camaeel,

Thank you for your suggestion.
The Talos packer template was based on [kubebn/talos-proxmox-kaas](https://github.com/kubebn/talos-proxmox-kaas), if you are planning to contribute, I believe it is better to do it at the source repo. 
This repo was created to setup GitOps for my home-lab IaC sometime in the future similar to [c0depool/c0depool-k8s-ops](https://github.com/c0depool/c0depool-k8s-ops).

**Comment by camaeel** [comment]
Thanx, I will  probably have my own implementation at the end so it fits rest of my setup.

**Comment by camaeel** [comment]
Work in progress here: https://github.com/camaeel/proxmox-talos-cluster/tree/packer
Seems to work but I would like to add few improvements.
